FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Malcaba.MovieCollector.App/Malcaba.MovieCollector.App.csproj", "Malcaba.MovieCollector.App/"]
RUN dotnet restore "Malcaba.MovieCollector.App/Malcaba.MovieCollector.App.csproj"
COPY . .
WORKDIR "/src/Malcaba.MovieCollector.App"
RUN dotnet build "Malcaba.MovieCollector.App.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Malcaba.MovieCollector.App.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Malcaba.MovieCollector.App.dll"]
